# Generated by Django 2.2.24 on 2022-08-12 15:55

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_flats = Flat.objects.filter(construction_year__gte=2015)
    new_flats.update(new_building=True)
    old_flats = Flat.objects.filter(construction_year__lt=2015)
    old_flats.update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220809_1950'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field)
    ]
