# Generated by Django 2.2.24 on 2022-08-12 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_auto_20220812_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Кто пожаловался')),
                ('flat', models.CharField(max_length=200, verbose_name='Квартира, на которую пожаловались')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('user', models.ForeignKey(on_delete='Пользователь', related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
