# Generated by Django 2.2.24 on 2022-08-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete='Квартира, на которую пожаловались', related_name='complaints', to='property.Flat'),
        ),
    ]
