# Generated by Django 2.2.24 on 2022-09-06 16:33
import phonenumbers

from django.db import migrations

def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
            number = flat.owners_phonenumber
            if number[0] == '8':
                splited_number = list(number)
                splited_number[0] = '+7'
                splited_number = ''.join(splited_number)
                number = phonenumbers.parse(splited_number)
            else:
                number = phonenumbers.parse(number, 'RU')
            if phonenumbers.is_valid_number(number):
                    flat.owner_pure_phone = phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.E164)
                    flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220819_1849'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone, move_backward)
    ]
