# Generated by Django 2.2.24 on 2022-10-04 16:25

from django.db import migrations


def add_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            owner = flat.owner,
            owners_phonenumber = flat.owners_phonenumber,
            owner_pure_phonenumber = flat.owner_pure_phone,
            flat = flat            
        )

    

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_owner'),
    ]

    operations = [
        migrations.RunPython(add_owners)
    ]
