# Generated by Django 2.2.24 on 2022-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20221004_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flat',
        ),
        migrations.AddField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.Flat', verbose_name='Квартиры, в собственности пользователя'),
        ),
    ]
